version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
  post_build:
    commands:
      - echo Eureka Server Build completed successfully
artifacts:
  files:
    - target/eureka-server.jar
  discard-paths: yes